version: "3.8"

services:
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "3001:3000"
    depends_on:
      - db

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: NDT-Timesheet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
